version: '3.8'

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: smartqueue-mailpit
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped
    networks:
      - smartqueue

networks:
  smartqueue:
    driver: bridge
