# Generated by Django 4.2.25 on 2025-10-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "Question générale"),
                            ("support", "Support technique"),
                            ("partnership", "Partenariat"),
                            ("billing", "Facturation"),
                            ("other", "Autre"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Sujet",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
