# Generated by Django 4.2.25 on 2025-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='counter_number',
            field=models.IntegerField(blank=True, help_text="Numéro du guichet de l'agent", null=True),
        ),
    ]
