# Generated by Django 4.2.25 on 2025-10-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="counter_number",
            field=models.IntegerField(
                blank=True, help_text="Numéro du guichet de l'agent", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
