# Generated by Django 4.2.25 on 2025-10-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_agentprofile_counter_number_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_company_name",
            field=models.CharField(
                blank=True,
                help_text="Nom d'entreprise en attente de création du tenant",
                max_length=255,
                null=True,
            ),
        ),
    ]
