# Generated by Django 4.2.25 on 2025-10-03 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email de l'utilisateur au moment de l'action",
                        max_length=254,
                    ),
                ),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("call_ticket", "Appel ticket"),
                            ("transfer_ticket", "Transfert ticket"),
                            ("close_ticket", "Clôture ticket"),
                            ("mark_no_show", "Marquage no-show"),
                            ("change_status", "Changement statut"),
                            ("export_data", "Export de données"),
                            ("settings_change", "Modification paramètres"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type de ressource (Ticket, Queue, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(help_text="ID de la ressource", max_length=255),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changements effectués (before/after)",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, help_text="URL de l'API appelée", max_length=255
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="audit_logs_tenant__0b1a88_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                ],
            },
        ),
    ]
