# Generated by Django 4.2.25 on 2025-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la fonctionnalité", max_length=100
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Clé unique", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description de la fonctionnalité"),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Fonctionnalité activée"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("experimental", "Experimental"),
                            ("beta", "Beta"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform_name",
                    models.CharField(
                        default="SmartQueue",
                        help_text="Nom de la plateforme",
                        max_length=100,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        help_text="Langue par défaut",
                        max_length=10,
                    ),
                ),
                (
                    "default_timezone",
                    models.CharField(
                        default="Africa/Dakar",
                        help_text="Fuseau horaire par défaut",
                        max_length=50,
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="XOF", help_text="Devise par défaut", max_length=10
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="Mode maintenance activé"
                    ),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(
                        default=True, help_text="Autoriser les nouvelles inscriptions"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Activer les notifications par email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=True, help_text="Activer les notifications par SMS"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, help_text="Activer les notifications push"
                    ),
                ),
                (
                    "max_upload_size_mb",
                    models.IntegerField(
                        default=10, help_text="Taille maximale de téléchargement en MB"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        default=60, help_text="Délai d'expiration de session en minutes"
                    ),
                ),
                (
                    "password_min_length",
                    models.IntegerField(
                        default=8, help_text="Longueur minimale du mot de passe"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True, help_text="Exiger la vérification de l'email"
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False,
                        help_text="Exiger l'authentification à deux facteurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Système",
                "verbose_name_plural": "Configuration Système",
            },
        ),
    ]
