# Generated by Django 4.2.25 on 2025-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_featureflag_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_from_email",
            field=models.EmailField(
                default="noreply@smartqueue.app",
                help_text="Email d'expéditeur",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_host",
            field=models.CharField(
                default="localhost", help_text="Serveur SMTP", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_password",
            field=models.CharField(
                blank=True, help_text="Mot de passe SMTP", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_port",
            field=models.IntegerField(default=1025, help_text="Port SMTP"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False, help_text="Utiliser SSL"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_use_tls",
            field=models.BooleanField(default=False, help_text="Utiliser TLS"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="smtp_username",
            field=models.CharField(
                blank=True, help_text="Nom d'utilisateur SMTP", max_length=255
            ),
        ),
    ]
