# Generated by Django 4.2.25 on 2025-10-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("queues", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueassignment",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_assignments",
                to="users.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="queueassignment",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="queues.queue",
            ),
        ),
        migrations.AddField(
            model_name="queueassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queues",
                to="queues.service",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to="queues.site",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("tenant", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("tenant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="queueassignment",
            unique_together={("queue", "agent")},
        ),
        migrations.AlterUniqueTogether(
            name="queue",
            unique_together={("tenant", "slug")},
        ),
    ]
