# Generated by Django 4.2.25 on 2025-10-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_initial"),
        ("queues", "0003_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="site",
            name="email",
        ),
        migrations.RemoveField(
            model_name="site",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="site",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="site",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="site",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="service",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="queues.site",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("tenant", "name", "site")},
        ),
    ]
