# Generated by Django 4.2.25 on 2025-10-21 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_coupon_couponusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0002_oauth_connection"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="oauthconnection",
            name="unique_user_provider",
        ),
        migrations.RenameIndex(
            model_name="oauthconnection",
            new_name="oauth_conne_provide_ddeae9_idx",
            old_name="oauth_conn_provide_idx",
        ),
        migrations.RenameIndex(
            model_name="oauthconnection",
            new_name="oauth_conne_user_id_267b07_idx",
            old_name="oauth_conn_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordhistory",
            new_name="password_hi_user_id_f4f4ce_idx",
            old_name="password_h_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="securityalert",
            new_name="security_al_severit_6bd218_idx",
            old_name="security_al_severit_idx",
        ),
        migrations.RenameIndex(
            model_name="securityalert",
            new_name="security_al_alert_t_3110ff_idx",
            old_name="security_al_alert_t_idx",
        ),
        migrations.RenameIndex(
            model_name="securityevent",
            new_name="security_ev_event_t_0dd22d_idx",
            old_name="security_ev_event_t_idx",
        ),
        migrations.RenameIndex(
            model_name="securityevent",
            new_name="security_ev_severit_88653d_idx",
            old_name="security_ev_severit_idx",
        ),
        migrations.RenameIndex(
            model_name="securityevent",
            new_name="security_ev_ip_addr_b3ff8b_idx",
            old_name="security_ev_ip_addr_idx",
        ),
        migrations.RenameIndex(
            model_name="securityevent",
            new_name="security_ev_user_id_70c595_idx",
            old_name="security_ev_user_id_idx",
        ),
        migrations.AlterField(
            model_name="passwordpolicy",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oauthconnection",
            unique_together={("user", "provider")},
        ),
    ]
