# Generated by Django 4.2.25 on 2025-10-02 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("language", models.CharField(default="fr", max_length=10)),
                ("notify_sms", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=False)),
                ("notify_whatsapp", models.BooleanField(default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champs personnalisés par tenant",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ("last_name", "first_name"),
                "unique_together": {("tenant", "phone")},
            },
        ),
    ]
