# Generated by Django 4.2.25 on 2025-10-13 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_agents",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_queues",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_sites",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="tenant",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="suspension_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_ends_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(default="trial", max_length=50),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Essai gratuit"),
                            ("active", "Actif"),
                            ("past_due", "Paiement en retard"),
                            ("suspended", "Suspendu"),
                            ("cancelled", "Annulé"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("monthly_price", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("starts_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "current_period_start",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("trial_ends_at", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                (
                    "external_subscription_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                ("subtotal", models.PositiveIntegerField(default=0)),
                ("tax", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("amount_paid", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("open", "En attente"),
                            ("paid", "Payée"),
                            ("void", "Annulée"),
                            ("uncollectible", "Impayée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("external_invoice_id", models.CharField(blank=True, max_length=255)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="tenants.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "invoices",
                "ordering": ["-invoice_date"],
            },
        ),
    ]
