# Generated by Django 4.2.25 on 2025-10-13 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_address_tenant_company_name_tenant_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("card", "Carte bancaire"),
                            ("bank_transfer", "Virement bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("cash", "Espèces"),
                            ("check", "Chèque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("orange_money", "Orange Money"),
                            ("wave", "Wave"),
                            ("free_money", "Free Money"),
                            ("e_money", "e-Money (Ecobank)"),
                            ("yoomee_money", "YooMee Money"),
                            ("mtn_money", "MTN Mobile Money"),
                            ("moov_money", "Moov Money"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("account_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("is_default", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
                "db_table": "payment_methods",
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="XOF", max_length=3),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="XOF", max_length=3),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Réussie"),
                            ("failed", "Échouée"),
                            ("cancelled", "Annulée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("payment_phone", models.CharField(blank=True, max_length=20)),
                ("payer_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="tenants.invoice",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="tenants.paymentmethod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
