# Generated by Django 4.2.25 on 2025-10-13 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_paymentmethod_alter_invoice_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("features", models.JSONField(default=list)),
                ("max_sites", models.IntegerField(default=1)),
                ("max_agents", models.IntegerField(default=5)),
                ("max_queues", models.IntegerField(default=3)),
                ("max_tickets_per_month", models.IntegerField(default=500)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "db_table": "subscription_plans",
                "ordering": ["price_monthly"],
            },
        ),
    ]
