# Generated by Django 4.2.25 on 2025-10-14 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_subscriptionplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed_amount", "Montant fixe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=0, help_text="0 = illimité")),
                ("max_uses_per_customer", models.IntegerField(default=1)),
                ("current_uses", models.IntegerField(default=0)),
                (
                    "customer_eligibility",
                    models.CharField(
                        choices=[
                            ("all", "Tous les clients"),
                            ("new_customers", "Nouveaux clients uniquement"),
                            ("existing_customers", "Clients existants uniquement"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("minimum_purchase_amount", models.IntegerField(default=0)),
                ("first_payment_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="tenants.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code promo",
                "verbose_name_plural": "Codes promo",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_amount", models.IntegerField()),
                ("discount_amount", models.IntegerField()),
                ("final_amount", models.IntegerField()),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="tenants.coupon",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.invoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de coupon",
                "verbose_name_plural": "Utilisations de coupons",
                "db_table": "coupon_usages",
                "ordering": ["-created_at"],
            },
        ),
    ]
