# Generated by Django 4.2.25 on 2025-10-29 13:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_coupon_couponusage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Plan de souscription",
                "verbose_name_plural": "Plans de souscription",
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_monthly",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_yearly",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="yearly_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="tenants.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_agents",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_queues",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_sites",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_tickets_per_month",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
