# Generated by Django 4.2.25 on 2025-10-29 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_migrate_plan_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('number_of_installments', models.PositiveIntegerField()),
                ('installment_amount', models.PositiveIntegerField()),
                ('frequency_days', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('accepted', 'Accepté'), ('active', 'En cours'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('defaulted', 'En défaut')], default='proposed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='tenants.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
                'db_table': 'payment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('email', 'Email de relance'), ('sms', 'SMS de relance'), ('call', 'Appel téléphonique'), ('suspension', 'Suspension du service'), ('legal', 'Action légale')], max_length=20)),
                ('days_overdue', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('sent', 'Envoyée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('result_message', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('sms_body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_actions', to='tenants.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_actions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Action de relance',
                'verbose_name_plural': 'Actions de relance',
                'db_table': 'dunning_actions',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='tenants.paymentplan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='tenants.transaction')),
            ],
            options={
                'verbose_name': 'Échéance de plan',
                'verbose_name_plural': 'Échéances de plan',
                'db_table': 'payment_plan_installments',
                'ordering': ['installment_number'],
                'unique_together': {('payment_plan', 'installment_number')},
            },
        ),
    ]
