# Generated by Django 4.2.25 on 2025-10-02 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("checked_in", "Présent"),
                            ("cancelled", "Annulé"),
                            ("completed", "Terminé"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "appointments",
                "ordering": ("starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("app", "App"),
                            ("qr", "QR"),
                            ("whatsapp", "WhatsApp"),
                            ("kiosk", "Borne"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("appele", "Appelé"),
                            ("en_service", "En service"),
                            ("pause", "En pause"),
                            ("transfere", "Transféré"),
                            ("clos", "Clôturé"),
                            ("no_show", "No show"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("eta_seconds", models.IntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_phone", models.CharField(blank=True, max_length=32)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tickets",
                "ordering": ("created_at",),
            },
        ),
    ]
