# Generated by Django 4.2.25 on 2025-10-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_initial"),
        ("customers", "__first__"),
        ("queues", "0003_initial"),
        ("tickets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="users.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="queues.queue",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="users.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="queue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="queues.queue",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="queues.service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
    ]
