# Generated by Django 4.2.25 on 2025-10-02 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queues", "0003_initial"),
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("device_id", models.CharField(max_length=255, unique=True)),
                (
                    "language_options",
                    models.JSONField(
                        blank=True, default=list, help_text='["fr", "en", "wo"]'
                    ),
                ),
                ("require_phone", models.BooleanField(default=True)),
                ("require_name", models.BooleanField(default=False)),
                ("enable_appointment_checkin", models.BooleanField(default=True)),
                ("has_printer", models.BooleanField(default=True)),
                ("printer_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                (
                    "available_queues",
                    models.ManyToManyField(
                        help_text="Files disponibles sur cette borne",
                        related_name="kiosks",
                        to="queues.queue",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiosks",
                        to="queues.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "kiosks",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Display",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("main", "Écran principal"),
                            ("counter", "Écran guichet"),
                            ("waiting", "Salle d'attente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="ID unique du device", max_length=255, unique=True
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        default="grid", help_text="grid, list, etc.", max_length=50
                    ),
                ),
                (
                    "theme",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Personnalisation couleurs/logo",
                    ),
                ),
                ("auto_refresh_seconds", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                (
                    "queues",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Files affichées sur cet écran",
                        related_name="displays",
                        to="queues.queue",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="displays",
                        to="queues.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "displays",
                "ordering": ("name",),
            },
        ),
    ]
