# Generated by Django 4.2.25 on 2025-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='background_image',
            field=models.URLField(blank=True, help_text='Image de fond pour la zone média', null=True),
        ),
        migrations.AddField(
            model_name='display',
            name='custom_message',
            field=models.TextField(blank=True, default='Votre bannière de messages à la clientèle', help_text="Message principal affiché en bas de l'écran"),
        ),
        migrations.AddField(
            model_name='display',
            name='message_position',
            field=models.CharField(choices=[('top', 'Haut'), ('bottom', 'Bas'), ('both', 'Haut et Bas')], default='bottom', max_length=20),
        ),
        migrations.AddField(
            model_name='display',
            name='secondary_message',
            field=models.TextField(blank=True, help_text='Message secondaire (défilant)'),
        ),
        migrations.AddField(
            model_name='display',
            name='show_video',
            field=models.BooleanField(default=True, help_text='Afficher la zone vidéo/image'),
        ),
        migrations.AddField(
            model_name='display',
            name='ticket_colors',
            field=models.JSONField(blank=True, default=dict, help_text='{"queue_id": "#color"} - Couleur par file'),
        ),
        migrations.AddField(
            model_name='display',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL vidéo YouTube, Vimeo, ou fichier', null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='layout',
            field=models.CharField(default='split', help_text='split, grid, list, fullscreen', max_length=50),
        ),
    ]
